name: Self-Hosted
on: [workflow_dispatch]
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: self-hosted
        shell: bash
        run: |
          echo: "Runner Name: '${{ runner.name }}'"
          echo: "Runner OS: '${{ runner.os }}'"
          echo: "Runner Arch: '${{ runner.arch }}'"
            